### ISSUE TITLE
ERROR: Content of 'https://github.com/JanWielemaker/geoip/archive/V0.9.0.zip' has changed.

### ISSUE THREAD

**Issue by mlliarm** [JanWielemaker/geoip#2]
Hello Jan !

I tried to install it according to the instructions in the README.md, and after installing the `*.deb` packages, and running `pack_install(geoip)` from `swipl` I get the following:

> % Contacting server at http://www.swi-prolog.org/pack/query ... ok
> Install geoip@0.9.0 from https://github.com/JanWielemaker/geoip/archive/V0.9.0.zip Y/n? 
> % Contacting server at http://www.swi-prolog.org/pack/query ...
> ERROR: Server reported the following error:
> ERROR: Content of 'https://github.com/JanWielemaker/geoip/archive/V0.9.0.zip' has changed.
> Pack may be compromised.  Continue anyway y/N?

I pressed N for "no" for the time being, just thought I should report this.

*My machine:*
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.2 LTS
> Release:	16.04
> Codename:	xenial

*Version of Swi-Prolog:*
>Package: swi-prolog                      
> State: installed
> Automatically installed: no
> Version: 7.2.3-2
> Priority: optional
> Section: universe/interpreters
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Architecture: amd64
> Uncompressed Size: 22,5 k
> Depends: swi-prolog-nox (= 7.2.3-2), swi-prolog-x (= 7.2.3-2)

*uname -a gives*
> Linux Newton 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thank you !

**Comment by JanWielemaker** [comment]
You can simply say yes.  It turns out that the content of release zip files on github is not stable.  We need some hack around that or file an issue at github to see whether they have an option to avoid that.

**Comment by mlliarm** [comment]
Thanks for the reply Jan ! I'll add your reply and the error message to the README.md and send a pull request then, if you agree.

**Comment by JanWielemaker** [comment]
It is basically not an issue of this package but in general of the pack infrastructure and how the pack system relates to github release mechanism.   I'd rather see that resolved then having warnings in the README of all individual packages.

**Comment by mlliarm** [comment]
Alright Jan, I see what you mean. Thank you very much, I'll install it right away and keep the fork for future reference.
